# Logging configuration
logging:
  log_file: data/processed/system.log
  log_level: INFO

preprocessing:
  # Stopwords configuration (choose one)
  extra_stopwords: ["_start_article_"]  # Add to default English stopwords
  # stopwords: ["word1", "word2"]  # Completely override default stopwords
# Data configuration
data:
  raw_data_path: data/raw/validation # Path to raw data files
  # raw_data_path: data/raw/sample_validation.parquet  # Path to raw data files

# Feature extraction configuration
feature_extraction:
  method: ngram # Options: ngram(for minhash) | token,vectorize,frequency(for simhash)
  ngram_size: 3 # Value of n in n-gram

# Fingerprint generation configuration
fingerprint:
  method: minhash  # Options: minhash, simhash, bitsampling, hybrid
  num_hashes: 64  # Number of hash functions for MinHash
  hash_bits: 24  # Number of signature bits for SimHash and BitSampling
  sample_size: 32  # Number of sampling bits for BitSampling
  seed: 42  # Random seed

# LSH index configuration
lsh:
  method: minhash  # Options: minhash, simhash, bitsampling, hybrid
  num_bands: 10  # Number of bands for MinHash
  rows_per_band: 5  # Number of rows per band
  radius: 1  # Hamming distance radius for SimHash
  num_hash_tables: 2  # Number of hash tables for BitSampling
  bits_per_table: 32  # Number of sampling bits per hash table
  # Parameters specific to hybrid methods
  minhash_num_bands: 20  # Number of bands for MinHash in hybrid methods
  minhash_rows_per_band: 5  # Number of rows per band for MinHash in hybrid methods
  simhash_radius: 1  # Hamming distance radius for SimHash in hybrid methods
  merge_strategy: weighted  # Merge strategy for hybrid methods: union/intersection/two-stage/weighted
  weights:  # Configuration for weighted strategy
    minhash: 0.95  # Weight for MinHash
    simhash: 0.05  # Weight for SimHash
    weighted_score_threshold: 0.65  # Weighted score threshold
    minhash_score_threshold: 0.3  # Minimum score threshold for MinHash

# Parallel processing configuration
parallel:
  enable: False # Enable parallel processing
  data_loader_parallel: False # Enable parallel data loading (not necessary)
  preprocess_parallel: True # Enable parallel preprocessing (recommended)
  feature_extraction_parallel: true # Enable parallel feature extraction (recommended)
  fingerprint_parallel: true # Enable parallel fingerprint generation ((simhash,frequency) recommended, (simhash,vectorize) not recommended)
  thread_pool_size: 4 # Number of threads for I/O-intensive tasks
  process_pool_size: 8 # Number of processes for CPU-intensive tasks
  use_memory_cache: True # Enable memory caching

# Output configuration
output:
  fingerpritnts_path: data/processed/bit_validation_fingerprints.csv # Path to save fingerprints
  evaluation_output_path: data/processed # Path to save evaluation result plots
  results_path: data/results/bit_validation_candidate_pairs.csv # Path to save candidate pair results
  pipeline_output_path: data/processed/bit_validation_pipeline_output.csv # Path to save pipeline output
  evaluation_html_path: data/results/bit_validation_evaluation.html # Path to save evaluation result HTML