# 日志配置
logging:
  log_file: data/processed/system.log
  log_level: INFO
  

# 数据配置
data:
  raw_data_path: data/raw/test/0000.parquet  # 原始数据文件路径
  # raw_data_path: data/raw/sample_test.parquet  # 原始数据文件路径

# 特征提取配置
feature_extraction:
  method: token  # 可选值: ngram, token, vectorize
  ngram_size: 3  # n-gram 的 n 值

# 指纹生成配置
fingerprint:
  method: simhash  # 可选值: minhash, simhash, bitsampling
  num_hashes: 100  # MinHash 的哈希函数数量
  hash_bits: 32  # SimHash 和 BitSampling 的签名位数
  sample_size: 32  # BitSampling 的采样位数
  seed: 42  # 随机种子

# LSH 索引配置
lsh:
  method: simhash  # 可选值: minhash, simhash, bitsampling
  num_bands: 20  # MinHash 的 band 数量
  rows_per_band: 5  # 每个 band 的行数
  radius: 1  # SimHash 的 Hamming 距离半径
  num_hash_tables: 2  # BitSampling 的哈希表数量
  bits_per_table: 32  # 每个哈希表的采样位数

# 评估配置
evaluation:
  # ground_truth_path: data/ground_truth/ground_truth.csv  # 真实标签文件路径

# 并行处理配置
parallel:
  enabled: false  # 是否启用并行处理
  thread_pool_size: 4  # I/O密集型任务线程数
  process_pool_size: 8  # CPU密集型任务进程数
  batch_size: 1000  # 指纹生成的批处理大小
  use_memory_cache: true  # 是否使用内存缓存

# 输出配置
output:
  fingerpritnts_path: data/processed/fingerprints.csv  # 指纹输出路径
  evaluation_output_path: data/processed  # 评估结果图保存路径
  results_path: data/results/candidate_pairs_sampling.csv  # 候选对结果保存路径
  pipeline_output_path: data/processed/pipeline_output.csv  # 流水线输出路径